### ISSUE TITLE
object-storage-relation-changed hook fails during startup causing `error` status

### ISSUE THREAD

**Issue by ca-scribner** [canonical/argo-operators#9]
During startup when first receiving an `object-storage-relation-changed` hook (after object storage has come online) the following status is observed:

```
Unit                Workload  Agent  Address      Ports     Message
argo-controller/0*  error     idle                          hook failed: "object-storage-relation-changed" for minio:object-storage
minio/0*            active    idle   10.1.182.98  9000/TCP  
```

with corresponding `debug-log`s:
```
application-argo-controller: 08:55:39 INFO juju.worker.caasoperator.uniter.argo-controller/0 awaiting error resolution for "relation-changed" hook
application-argo-controller: 08:55:44 INFO juju.worker.caasoperator.uniter.argo-controller/0 awaiting error resolution for "relation-changed" hook
application-argo-controller: 08:55:45 INFO unit.argo-controller/0.juju-log object-storage:0: RELATIONS: [<ops.model.Relation object-storage:0>]
application-argo-controller: 08:55:45 INFO unit.argo-controller/0.juju-log object-storage:0: RESOURCES: <ops.model.Resources object at 0x7f70dc812490>
application-argo-controller: 08:55:45 INFO unit.argo-controller/0.juju-log object-storage:0: dir(resources): ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_backend', '_paths', 'fetch']
application-argo-controller: 08:55:46 INFO unit.argo-controller/0.juju-log object-storage:0: image_details = {'imagePath': 'argoproj/workflow-controller:v3.1.8', 'username': '', 'password': ''}
application-argo-controller: 08:55:46 INFO unit.argo-controller/0.juju-log object-storage:0: self.image = <oci_image.OCIImageResource object at 0x7f70dc812e20>
application-argo-controller: 08:55:46 INFO unit.argo-controller/0.juju-log object-storage:0: using executorImage argoproj/argoexec:v3.1.8
application-argo-controller: 08:55:46 INFO unit.argo-controller/0.juju-log object-storage:0: using executorImage argoproj/argoexec:v3.1.8
application-argo-controller: 08:55:46 INFO juju.worker.caasoperator.uniter.argo-controller/0.operation ran "object-storage-relation-changed" hook (via hook dispatching script: dispatch)
application-argo-controller: 08:55:11 INFO juju.worker.caasoperator.runner runner is dying
application-argo-controller: 08:55:11 WARNING juju.worker.caasoperator operator "argo-controller" is shutting down, err: catacomb 0xc00044d680 is dying
application-argo-controller: 08:55:11 INFO juju.worker.logger logger worker stopped
application-argo-controller: 08:55:11 ERROR unit.argo-controller/0.juju-log object-storage:0: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-argo-controller-0/charm/venv/ops/model.py", line 1049, in _run
    result = run(args, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-argo-controller-0/config-get', '--format=json')' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./src/charm.py", line 279, in <module>
    main(ArgoControllerCharm)
  File "/var/lib/juju/agents/unit-argo-controller-0/charm/venv/ops/main.py", line 402, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-argo-controller-0/charm/venv/ops/main.py", line 140, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-argo-controller-0/charm/venv/ops/framework.py", line 278, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-argo-controller-0/charm/venv/ops/framework.py", line 722, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-argo-controller-0/charm/venv/ops/framework.py", line 767, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 89, in main
    "containerRuntimeExecutor": self.model.config["executor"],
  File "/var/lib/juju/agents/unit-argo-controller-0/charm/venv/ops/model.py", line 383, in __getitem__
    return self._data[key]
  File "/var/lib/juju/agents/unit-argo-controller-0/charm/venv/ops/model.py", line 367, in _data
    data = self._lazy_data = self._load()
  File "/var/lib/juju/agents/unit-argo-controller-0/charm/venv/ops/model.py", line 773, in _load
    return self._backend.config_get()
  File "/var/lib/juju/agents/unit-argo-controller-0/charm/venv/ops/model.py", line 1118, in config_get
    return self._run('config-get', return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-argo-controller-0/charm/venv/ops/model.py", line 1051, in _run
    raise ModelError(e.stderr)
ops.model.ModelError: b'ERROR connection is shut down\n'
application-argo-controller: 08:55:11 ERROR juju.worker.caasoperator.uniter.argo-controller/0.operation hook "object-storage-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
application-argo-controller: 08:55:11 INFO juju.worker.caasoperator.uniter.argo-controller/0 unit "argo-controller/0" shutting down: (re)starting watcher: connection is shut down
application-argo-controller: 08:55:11 INFO juju.worker.caasoperator.runner stopped "argo-controller/0", err: leadership failure: error making a leadership claim: connection is shut down
application-argo-controller: 08:55:11 ERROR juju.worker.caasoperator.runner exited "argo-controller/0": leadership failure: error making a leadership claim: connection is shut down
application-argo-controller: 08:55:17 INFO juju.api cannot resolve "controller-service.controller-uk8s.svc.cluster.local": i/o timeout
application-argo-controller: 08:55:17 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [b90fec] "application-argo-controller" cannot open api: cannot resolve "controller-service.controller-uk8s.svc.cluster.local": i/o timeout
application-argo-controller: 08:55:23 INFO juju.api cannot resolve "controller-service.controller-uk8s.svc.cluster.local": i/o timeout
application-argo-controller: 08:55:23 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [b90fec] "application-argo-controller" cannot open api: cannot resolve "controller-service.controller-uk8s.svc.cluster.local": i/o timeout
application-argo-controller: 08:55:30 INFO juju.api cannot resolve "controller-service.controller-uk8s.svc.cluster.local": i/o timeout
application-argo-controller: 08:55:31 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [b90fec] "application-argo-controller" cannot open api: cannot resolve "controller-service.controller-uk8s.svc.cluster.local": i/o timeout
application-argo-controller: 08:55:36 INFO juju.api cannot resolve "controller-service.controller-uk8s.svc.cluster.local": operation was canceled
application-argo-controller: 08:55:36 INFO juju.api connection established to "wss://10.152.183.192:17070/model/b90fec21-f9ea-4d69-8c29-84f397b9d56d/api"
application-argo-controller: 08:55:36 INFO juju.worker.apicaller [b90fec] "application-argo-controller" successfully connected to "10.152.183.192:17070"
application-argo-controller: 08:55:36 INFO juju.worker.migrationminion migration phase is now: NONE
application-argo-controller: 08:55:36 INFO juju.worker.caasupgrader abort check blocked until version event received
application-argo-controller: 08:55:36 INFO juju.worker.caasupgrader unblocking abort check
application-argo-controller: 08:55:36 INFO juju.worker.logger logger worker started
application-argo-controller: 08:55:36 WARNING juju.worker.proxyupdater unable to set snap core settings [proxy.http= proxy.https= proxy.store=]: exec: "snap": executable file not found in $PATH, output: ""
application-argo-controller: 08:55:39 INFO juju.worker.caasoperator operator "argo-controller" started
application-argo-controller: 08:55:39 INFO juju.worker.caasoperator.runner start "argo-controller/0"
application-argo-controller: 08:55:39 INFO juju.agent.tools ensure jujuc symlinks in /var/lib/juju/tools/unit-argo-controller-0
application-argo-controller: 08:55:39 INFO juju.worker.caasoperator.uniter.argo-controller/0.relation joining relation "argo-controller:object-storage minio:object-storage"
application-argo-controller: 08:55:39 INFO juju.worker.caasoperator.uniter.argo-controller/0.relation joined relation "argo-controller:object-storage minio:object-storage"
application-argo-controller: 08:55:39 INFO juju.worker.leadership argo-controller/0 promoted to leadership of argo-controller
application-argo-controller: 08:55:39 INFO juju.worker.caasoperator.uniter.argo-controller/0 unit "argo-controller/0" started
application-argo-controller: 08:55:39 INFO juju.worker.caasoperator.uniter.argo-controller/0 hooks are retried true
```

This appears to caused by either a flaky response from `self.model.config[*]` or maybe model config will not be available during this type of hook?  

The error resolves itself quickly (a few seconds) and deployment completes, but the error itself will often cause false failures of CI or at minimum look worrying to the user.

**Comment by DomFleischmann** [comment]
I believe this has been fixed with later releases of argo-controller, please reopen if this still occurs.
